/**
 * Icon set — re-exported from lucide-react under the names the app already
 * imports, so every existing call site (`<MenuIcon className="h-5 w-5" />`)
 * keeps working while we get a consistent, professional icon library.
 *
 * lucide icons accept `className`, `size`, `strokeWidth`, and all SVG props.
 */
export {
  Menu as MenuIcon,
  X as XIcon,
  Home as HomeIcon,
  User as UserIcon,
  Settings as SettingsIcon,
  LogOut as LogOutIcon,
  ChevronDown as ChevronDownIcon,
  ChevronUp as ChevronUpIcon,
  ShieldCheck as ShieldIcon,
  Mail as MailIcon,
  Calendar as CalendarIcon,
  Users as UsersIcon,
  Search as SearchIcon,
  Plus as PlusIcon,
  Pencil as PencilIcon,
  Trash2 as TrashIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  LoaderCircle as SpinnerIcon,
  Server as ServerIcon,
  BarChart3 as ChartBarIcon,
  ArrowLeft as ArrowLeftIcon,
  RefreshCw as ArrowPathIcon,
  Eye as EyeIcon,
  Radio as BroadcastIcon,
  Receipt as ReceiptIcon,
  Tag as TagIcon,
  Wallet as WalletIcon,
  Copy as CopyIcon,
  Check as CheckIcon,
  ExternalLink as ExternalLinkIcon,
  Power as PowerIcon,
  Play as PlayIcon,
  // Extras used by the redesigned UI
  Sun as SunIcon,
  Moon as MoonIcon,
  Monitor as MonitorIcon,
  Bell as BellIcon,
  LayoutDashboard as LayoutDashboardIcon,
  CircleAlert as AlertIcon,
  Info as InfoIcon,
  TrendingUp as TrendingUpIcon,
  Activity as ActivityIcon,
  CreditCard as CreditCardIcon,
  Package as PackageIcon,
  ArrowRight as ArrowRightIcon,
  Filter as FilterIcon,
  MoreVertical as MoreVerticalIcon,
  Ban as BanIcon,
} from 'lucide-react';
